# Flat Files Docs

Access historical data in bulk via downloadable CSVs. If you need comprehensive datasets for extensive analysis, backtesting, or machine learning models, our Flat Files offer a great way to download large volumes of historical data.

In [1]:
aws_access_key_id = "b2efb6eb-09a9-470b-be7a-063ff3614bb2"
aws_secret_access_key = "gE_mClabKAWkIBuc36jStM5blbyqNUms"
s3_endpoint = "https://files.massive.com"
bucket_name = "flatfiles"

save_dir = "/Users/livardywufianto/Projects/Trading/vscode/technical-analysis/data/minute_aggs"

In [2]:
import boto3
from botocore.config import Config

# Initialize a session using your credentials
session = boto3.Session(
  aws_access_key_id=aws_access_key_id,
  aws_secret_access_key=aws_secret_access_key,
)

In [3]:
# Create a client with your session and specify the endpoint
s3 = session.client(
  's3',
  endpoint_url=s3_endpoint,
  config=Config(signature_version='s3v4'),
)

In [4]:
# List Example
# Initialize a paginator for listing objects
paginator = s3.get_paginator('list_objects_v2')

# Choose the appropriate prefix depending on the data you need:
# - 'global_crypto' for global cryptocurrency data
# - 'global_forex' for global forex data
# - 'us_indices' for US indices data
# - 'us_options_opra' for US options (OPRA) data
# - 'us_stocks_sip' for US stocks (SIP) data
prefix = 'us_stocks_sip'  # Example: Change this prefix to match your data need

In [5]:
# List objects using the selected prefix
for page in paginator.paginate(Bucket='flatfiles', Prefix=prefix):
  for obj in page['Contents']:
    print(obj['Key'])

# Copy example
# Specify the bucket name
bucket_name = bucket_name

# Specify the S3 object key name
object_key = 'us_stocks_sip/minute_aggs_v1/2026/05/2026-05-01.csv.gz'

# Specify the local file name and path to save the downloaded file
# This splits the object_key string by '/' and takes the last segment as the file name
local_file_name = object_key.split('/')[-1]

# This constructs the full local file path
local_file_path = save_dir + '/' + local_file_name

# Download the file
# s3.download_file(bucket_name, object_key, local_file_path)

us_stocks_sip/day_aggs_v1/2003/09/2003-09-10.csv.gz
us_stocks_sip/day_aggs_v1/2003/09/2003-09-11.csv.gz
us_stocks_sip/day_aggs_v1/2003/09/2003-09-12.csv.gz
us_stocks_sip/day_aggs_v1/2003/09/2003-09-15.csv.gz
us_stocks_sip/day_aggs_v1/2003/09/2003-09-16.csv.gz
us_stocks_sip/day_aggs_v1/2003/09/2003-09-17.csv.gz
us_stocks_sip/day_aggs_v1/2003/09/2003-09-18.csv.gz
us_stocks_sip/day_aggs_v1/2003/09/2003-09-19.csv.gz
us_stocks_sip/day_aggs_v1/2003/09/2003-09-22.csv.gz
us_stocks_sip/day_aggs_v1/2003/09/2003-09-23.csv.gz
us_stocks_sip/day_aggs_v1/2003/09/2003-09-24.csv.gz
us_stocks_sip/day_aggs_v1/2003/09/2003-09-25.csv.gz
us_stocks_sip/day_aggs_v1/2003/09/2003-09-26.csv.gz
us_stocks_sip/day_aggs_v1/2003/09/2003-09-29.csv.gz
us_stocks_sip/day_aggs_v1/2003/09/2003-09-30.csv.gz
us_stocks_sip/day_aggs_v1/2003/10/2003-10-01.csv.gz
us_stocks_sip/day_aggs_v1/2003/10/2003-10-02.csv.gz
us_stocks_sip/day_aggs_v1/2003/10/2003-10-03.csv.gz
us_stocks_sip/day_aggs_v1/2003/10/2003-10-06.csv.gz
us_stocks_sip/day_aggs_v1/2003/10/2003-10-07.csv.gz
us_stocks_sip/day_aggs_v1/2003/10/2003-10-08.csv.gz
us_stocks_sip/day_aggs_v1/2003/10/2003-10-09.csv.gz
us_stocks_sip/day_aggs_v1/2003/10/2003-10-10.csv.gz
us_stocks_sip/day_aggs_v1/2003/10/2003-10-13.csv.gz
us_stocks_sip/day_aggs_v1/2003/10/2003-10-14.csv.gz
us_stocks_sip/day_aggs_v1/2003/10/2003-10-15.csv.gz
us_stocks_sip/day_aggs_v1/2003/10/2003-10-16.csv.gz
us_stocks_sip/day_aggs_v1/2003/10/2003-10-17.csv.gz
us_stocks_sip/day_aggs_v1/2003/10/2003-10-20.csv.gz
us_stocks_sip/day_aggs_v1/2003/10/2003-10-21.csv.gz
us_stocks_sip/day_aggs_v1/2003/10/2003-10-22.csv.gz
us_stocks_sip/day_aggs_v1/2003/10/2003-10-23.csv.gz
us_stocks_sip/day_aggs_v1/2003/10/2003-10-24.csv.gz
us_stocks_sip/day_aggs_v1/2003/10/2003-10-27.csv.gz
us_stocks_sip/day_aggs_v1/2003/10/2003-10-28.csv.gz
us_stocks_sip/day_aggs_v1/2003/10/2003-10-29.csv.gz
us_stocks_sip/day_aggs_v1/2003/10/2003-10-30.csv.gz
us_stocks_sip/day_aggs_v1/2003/10/2003-10-31.csv.gz
us_stocks_sip/day_aggs_v1/2003/11/2003-11-03.csv.gz
us_stocks_sip/day_aggs_v1/2003/11/2003-11-04.csv.gz
us_stocks_sip/day_aggs_v1/2003/11/2003-11-05.csv.gz
us_stocks_sip/day_aggs_v1/2003/11/2003-11-06.csv.gz
us_stocks_sip/day_aggs_v1/2003/11/2003-11-07.csv.gz
us_stocks_sip/day_aggs_v1/2003/11/2003-11-10.csv.gz
us_stocks_sip/day_aggs_v1/2003/11/2003-11-11.csv.gz
us_stocks_sip/day_aggs_v1/2003/11/2003-11-12.csv.gz
us_stocks_sip/day_aggs_v1/2003/11/2003-11-13.csv.gz
us_stocks_sip/day_aggs_v1/2003/11/2003-11-14.csv.gz
us_stocks_sip/day_aggs_v1/2003/11/2003-11-17.csv.gz
us_stocks_sip/day_aggs_v1/2003/11/2003-11-18.csv.gz
us_stocks_sip/day_aggs_v1/2003/11/2003-11-19.csv.gz
us_stocks_sip/day_aggs_v1/2003/11/2003-11-20.csv.gz
us_stocks_sip/day_aggs_v1/2003/11/2003-11-21.csv.gz
us_stocks_sip/day_aggs_v1/2003/11/2003-11-24.csv.gz
us_stocks_sip/day_aggs_v1/2003/11/2003-11-25.csv.gz
us_stocks_sip/day_aggs_v1/2003/11/2003-11-26.csv.gz
us_stocks_sip/day_aggs_v1/2003/11/2003-11-28.csv.gz
us_stocks_sip/day_aggs_v1/2003/12/2003-12-01.csv.gz
us_stocks_sip/day_aggs_v1/2003/12/2003-12-02.csv.gz
us_stocks_sip/day_aggs_v1/2003/12/2003-12-03.csv.gz
us_stocks_sip/day_aggs_v1/2003/12/2003-12-04.csv.gz
us_stocks_sip/day_aggs_v1/2003/12/2003-12-05.csv.gz
us_stocks_sip/day_aggs_v1/2003/12/2003-12-08.csv.gz
us_stocks_sip/day_aggs_v1/2003/12/2003-12-09.csv.gz
us_stocks_sip/day_aggs_v1/2003/12/2003-12-10.csv.gz
us_stocks_sip/day_aggs_v1/2003/12/2003-12-11.csv.gz
us_stocks_sip/day_aggs_v1/2003/12/2003-12-12.csv.gz
us_stocks_sip/day_aggs_v1/2003/12/2003-12-15.csv.gz
us_stocks_sip/day_aggs_v1/2003/12/2003-12-16.csv.gz
us_stocks_sip/day_aggs_v1/2003/12/2003-12-17.csv.gz
us_stocks_sip/day_aggs_v1/2003/12/2003-12-18.csv.gz
us_stocks_sip/day_aggs_v1/2003/12/2003-12-19.csv.gz
us_stocks_sip/day_aggs_v1/2003/12/2003-12-22.csv.gz
us_stocks_sip/day_aggs_v1/2003/12/2003-12-23.csv.gz
us_stocks_sip/day_aggs_v1/2003/12/2003-12-24.csv.gz
us_stocks_sip/day_aggs_v1/2003/12/2003-12-26.csv.gz
us_stocks_sip/day_aggs_v1/2003/12/2003-12-29.csv.gz
us_stocks_sip/day_aggs_v1/2003/12/2003-12-30.csv.gz
us_stocks_sip/day_aggs_v1/2003/12/2003-12-31.csv.gz
us_stocks_sip/day_aggs_v1/2004/01/2004-01-02.csv.gz
us_stocks_sip/day_aggs_v1/2004/01/2004-01-05.csv.gz
us_stocks_sip/day_aggs_v1/2004/01/2004-01-06.csv.gz
us_stocks_sip/day_aggs_v1/2004/01/2004-01-07.csv.gz
us_stocks_sip/day_aggs_v1/2004/01/2004-01-08.csv.gz
us_stocks_sip/day_aggs_v1/2004/01/2004-01-09.csv.gz
us_stocks_sip/day_aggs_v1/2004/01/2004-01-12.csv.gz
us_stocks_sip/day_aggs_v1/2004/01/2004-01-13.csv.gz
us_stocks_sip/day_aggs_v1/2004/01/2004-01-14.csv.gz
us_stocks_sip/day_aggs_v1/2004/01/2004-01-15.csv.gz
us_stocks_sip/day_aggs_v1/2004/01/2004-01-16.csv.gz
us_stocks_sip/day_aggs_v1/2004/01/2004-01-20.csv.gz
us_stocks_sip/day_aggs_v1/2004/01/2004-01-21.csv.gz
us_stocks_sip/day_aggs_v1/2004/01/2004-01-22.csv.gz
us_stocks_sip/day_aggs_v1/2004/01/2004-01-23.csv.gz
us_stocks_sip/day_aggs_v1/2004/01/2004-01-26.csv.gz
us_stocks_sip/day_aggs_v1/2004/01/2004-01-27.csv.gz
us_stocks_sip/day_aggs_v1/2004/01/2004-01-28.csv.gz
us_stocks_sip/day_aggs_v1/2004/01/2004-01-29.csv.gz
us_stocks_sip/day_aggs_v1/2004/01/2004-01-30.csv.gz
us_stocks_sip/day_aggs_v1/2004/02/2004-02-02.csv.gz
us_stocks_sip/day_aggs_v1/2004/02/2004-02-03.csv.gz
us_stocks_sip/day_aggs_v1/2004/02/2004-02-04.csv.gz
us_stocks_sip/day_aggs_v1/2004/02/2004-02-05.csv.gz
us_stocks_sip/day_aggs_v1/2004/02/2004-02-06.csv.gz
us_stocks_sip/day_aggs_v1/2004/02/2004-02-09.csv.gz
us_stocks_sip/day_aggs_v1/2004/02/2004-02-10.csv.gz
us_stocks_sip/day_aggs_v1/2004/02/2004-02-11.csv.gz
us_stocks_sip/day_aggs_v1/2004/02/2004-02-12.csv.gz
us_stocks_sip/day_aggs_v1/2004/02/2004-02-13.csv.gz
us_stocks_sip/day_aggs_v1/2004/02/2004-02-17.csv.gz
us_stocks_sip/day_aggs_v1/2004/02/2004-02-18.csv.gz
us_stocks_sip/day_aggs_v1/2004/02/2004-02-19.csv.gz
us_stocks_sip/day_aggs_v1/2004/02/2004-02-20.csv.gz
us_stocks_sip/day_aggs_v1/2004/02/2004-02-23.csv.gz
us_stocks_sip/day_aggs_v1/2004/02/2004-02-24.csv.gz
us_stocks_sip/day_aggs_v1/2004/02/2004-02-25.csv.gz
us_stocks_sip/day_aggs_v1/2004/02/2004-02-26.csv.gz
us_stocks_sip/day_aggs_v1/2004/02/2004-02-27.csv.gz
us_stocks_sip/day_aggs_v1/2004/03/2004-03-01.csv.gz
us_stocks_sip/day_aggs_v1/2004/03/2004-03-02.csv.gz
us_stocks_sip/day_aggs_v1/2004/03/2004-03-03.csv.gz
us_stocks_sip/day_aggs_v1/2004/03/2004-03-04.csv.gz
us_stocks_sip/day_aggs_v1/2004/03/2004-03-05.csv.gz
us_stocks_sip/day_aggs_v1/2004/03/2004-03-08.csv.gz
us_stocks_sip/day_aggs_v1/2004/03/2004-03-09.csv.gz
us_stocks_sip/day_aggs_v1/2004/03/2004-03-10.csv.gz
us_stocks_sip/day_aggs_v1/2004/03/2004-03-11.csv.gz
us_stocks_sip/day_aggs_v1/2004/03/2004-03-12.csv.gz
us_stocks_sip/day_aggs_v1/2004/03/2004-03-15.csv.gz
us_stocks_sip/day_aggs_v1/2004/03/2004-03-16.csv.gz
us_stocks_sip/day_aggs_v1/2004/03/2004-03-17.csv.gz
us_stocks_sip/day_aggs_v1/2004/03/2004-03-18.csv.gz
us_stocks_sip/day_aggs_v1/2004/03/2004-03-19.csv.gz
us_stocks_sip/day_aggs_v1/2004/03/2004-03-22.csv.gz
us_stocks_sip/day_aggs_v1/2004/03/2004-03-23.csv.gz
us_stocks_sip/day_aggs_v1/2004/03/2004-03-24.csv.gz
us_stocks_sip/day_aggs_v1/2004/03/2004-03-25.csv.gz
us_stocks_sip/day_aggs_v1/2004/03/2004-03-26.csv.gz
us_stocks_sip/day_aggs_v1/2004/03/2004-03-29.csv.gz
us_stocks_sip/day_aggs_v1/2004/03/2004-03-30.csv.gz
us_stocks_sip/day_aggs_v1/2004/03/2004-03-31.csv.gz
us_stocks_sip/day_aggs_v1/2004/04/2004-04-01.csv.gz
us_stocks_sip/day_aggs_v1/2004/04/2004-04-02.csv.gz
us_stocks_sip/day_aggs_v1/2004/04/2004-04-05.csv.gz
us_stocks_sip/day_aggs_v1/2004/04/2004-04-06.csv.gz
us_stocks_sip/day_aggs_v1/2004/04/2004-04-07.csv.gz
us_stocks_sip/day_aggs_v1/2004/04/2004-04-08.csv.gz
us_stocks_sip/day_aggs_v1/2004/04/2004-04-12.csv.gz
us_stocks_sip/day_aggs_v1/2004/04/2004-04-13.csv.gz
us_stocks_sip/day_aggs_v1/2004/04/2004-04-14.csv.gz
us_stocks_sip/day_aggs_v1/2004/04/2004-04-15.csv.gz
us_stocks_sip/day_aggs_v1/2004/04/2004-04-16.csv.gz
us_stocks_sip/day_aggs_v1/2004/04/2004-04-19.csv.gz
us_stocks_sip/day_aggs_v1/2004/04/2004-04-20.csv.gz
us_stocks_sip/day_aggs_v1/2004/04/2004-04-21.csv.gz
us_stocks_sip/day_aggs_v1/2004/04/2004-04-22.csv.gz
us_stocks_sip/day_aggs_v1/2004/04/2004-04-23.csv.gz
us_stocks_sip/day_aggs_v1/2004/04/2004-04-26.csv.gz
us_stocks_sip/day_aggs_v1/2004/04/2004-04-27.csv.gz
us_stocks_sip/day_aggs_v1/2004/04/2004-04-28.csv.gz
us_stocks_sip/day_aggs_v1/2004/04/2004-04-29.csv.gz
us_stocks_sip/day_aggs_v1/2004/04/2004-04-30.csv.gz
us_stocks_sip/day_aggs_v1/2004/05/2004-05-03.csv.gz
us_stocks_sip/day_aggs_v1/2004/05/2004-05-04.csv.gz
us_stocks_sip/day_aggs_v1/2004/05/2004-05-05.csv.gz
us_stocks_sip/day_aggs_v1/2004/05/2004-05-06.csv.gz
us_stocks_sip/day_aggs_v1/2004/05/2004-05-07.csv.gz
us_stocks_sip/day_aggs_v1/2004/05/2004-05-10.csv.gz
us_stocks_sip/day_aggs_v1/2004/05/2004-05-11.csv.gz
us_stocks_sip/day_aggs_v1/2004/05/2004-05-12.csv.gz
us_stocks_sip/day_aggs_v1/2004/05/2004-05-13.csv.gz
us_stocks_sip/day_aggs_v1/2004/05/2004-05-14.csv.gz
us_stocks_sip/day_aggs_v1/2004/05/2004-05-17.csv.gz
us_stocks_sip/day_aggs_v1/2004/05/2004-05-18.csv.gz
us_stocks_sip/day_aggs_v1/2004/05/2004-05-19.csv.gz
us_stocks_sip/day_aggs_v1/2004/05/2004-05-20.csv.gz
us_stocks_sip/day_aggs_v1/2004/05/2004-05-21.csv.gz
us_stocks_sip/day_aggs_v1/2004/05/2004-05-24.csv.gz
us_stocks_sip/day_aggs_v1/2004/05/2004-05-25.csv.gz
us_stocks_sip/day_aggs_v1/2004/05/2004-05-26.csv.gz
us_stocks_sip/day_aggs_v1/2004/05/2004-05-27.csv.gz
us_stocks_sip/day_aggs_v1/2004/05/2004-05-28.csv.gz
us_stocks_sip/day_aggs_v1/2004/06/2004-06-01.csv.gz
us_stocks_sip/day_aggs_v1/2004/06/2004-06-02.csv.gz
us_stocks_sip/day_aggs_v1/2004/06/2004-06-03.csv.gz
us_stocks_sip/day_aggs_v1/2004/06/2004-06-04.csv.gz
us_stocks_sip/day_aggs_v1/2004/06/2004-06-07.csv.gz
us_stocks_sip/day_aggs_v1/2004/06/2004-06-08.csv.gz
us_stocks_sip/day_aggs_v1/2004/06/2004-06-09.csv.gz
us_stocks_sip/day_aggs_v1/2004/06/2004-06-10.csv.gz
us_stocks_sip/day_aggs_v1/2004/06/2004-06-14.csv.gz
us_stocks_sip/day_aggs_v1/2004/06/2004-06-15.csv.gz
us_stocks_sip/day_aggs_v1/2004/06/2004-06-16.csv.gz
us_stocks_sip/day_aggs_v1/2004/06/2004-06-17.csv.gz
us_stocks_sip/day_aggs_v1/2004/06/2004-06-18.csv.gz
us_stocks_sip/day_aggs_v1/2004/06/2004-06-21.csv.gz
us_stocks_sip/day_aggs_v1/2004/06/2004-06-22.csv.gz
us_stocks_sip/day_aggs_v1/2004/06/2004-06-23.csv.gz
us_stocks_sip/day_aggs_v1/2004/06/2004-06-24.csv.gz
us_stocks_sip/day_aggs_v1/2004/06/2004-06-25.csv.gz
us_stocks_sip/day_aggs_v1/2004/06/2004-06-28.csv.gz
us_stocks_sip/day_aggs_v1/2004/06/2004-06-29.csv.gz
us_stocks_sip/day_aggs_v1/2004/06/2004-06-30.csv.gz
us_stocks_sip/day_aggs_v1/2004/07/2004-07-01.csv.gz
us_stocks_sip/day_aggs_v1/2004/07/2004-07-02.csv.gz
us_stocks_sip/day_aggs_v1/2004/07/2004-07-06.csv.gz
us_stocks_sip/day_aggs_v1/2004/07/2004-07-07.csv.gz
us_stocks_sip/day_aggs_v1/2004/07/2004-07-08.csv.gz
us_stocks_sip/day_aggs_v1/2004/07/2004-07-09.csv.gz
us_stocks_sip/day_aggs_v1/2004/07/2004-07-12.csv.gz
us_stocks_sip/day_aggs_v1/2004/07/2004-07-13.csv.gz
us_stocks_sip/day_aggs_v1/2004/07/2004-07-14.csv.gz
us_stocks_sip/day_aggs_v1/2004/07/2004-07-15.csv.gz
us_stocks_sip/day_aggs_v1/2004/07/2004-07-16.csv.gz
us_stocks_sip/day_aggs_v1/2004/07/2004-07-19.csv.gz
us_stocks_sip/day_aggs_v1/2004/07/2004-07-20.csv.gz
us_stocks_sip/day_aggs_v1/2004/07/2004-07-21.csv.gz
us_stocks_sip/day_aggs_v1/2004/07/2004-07-22.csv.gz
us_stocks_sip/day_aggs_v1/2004/07/2004-07-23.csv.gz
us_stocks_sip/day_aggs_v1/2004/07/2004-07-26.csv.gz
us_stocks_sip/day_aggs_v1/2004/07/2004-07-27.csv.gz
us_stocks_sip/day_aggs_v1/2004/07/2004-07-28.csv.gz
us_stocks_sip/day_aggs_v1/2004/07/2004-07-29.csv.gz
us_stocks_sip/day_aggs_v1/2004/07/2004-07-30.csv.gz
us_stocks_sip/day_aggs_v1/2004/08/2004-08-02.csv.gz
us_stocks_sip/day_aggs_v1/2004/08/2004-08-03.csv.gz
us_stocks_sip/day_aggs_v1/2004/08/2004-08-04.csv.gz
us_stocks_sip/day_aggs_v1/2004/08/2004-08-05.csv.gz
us_stocks_sip/day_aggs_v1/2004/08/2004-08-06.csv.gz
us_stocks_sip/day_aggs_v1/2004/08/2004-08-09.csv.gz
us_stocks_sip/day_aggs_v1/2004/08/2004-08-10.csv.gz
us_stocks_sip/day_aggs_v1/2004/08/2004-08-11.csv.gz
us_stocks_sip/day_aggs_v1/2004/08/2004-08-12.csv.gz
us_stocks_sip/day_aggs_v1/2004/08/2004-08-13.csv.gz
us_stocks_sip/day_aggs_v1/2004/08/2004-08-16.csv.gz
us_stocks_sip/day_aggs_v1/2004/08/2004-08-17.csv.gz
us_stocks_sip/day_aggs_v1/2004/08/2004-08-18.csv.gz
us_stocks_sip/day_aggs_v1/2004/08/2004-08-19.csv.gz
us_stocks_sip/day_aggs_v1/2004/08/2004-08-20.csv.gz
us_stocks_sip/day_aggs_v1/2004/08/2004-08-23.csv.gz
us_stocks_sip/day_aggs_v1/2004/08/2004-08-24.csv.gz
us_stocks_sip/day_aggs_v1/2004/08/2004-08-25.csv.gz
us_stocks_sip/day_aggs_v1/2004/08/2004-08-26.csv.gz
us_stocks_sip/day_aggs_v1/2004/08/2004-08-27.csv.gz
us_stocks_sip/day_aggs_v1/2004/08/2004-08-30.csv.gz
us_stocks_sip/day_aggs_v1/2004/08/2004-08-31.csv.gz
us_stocks_sip/day_aggs_v1/2004/09/2004-09-01.csv.gz
us_stocks_sip/day_aggs_v1/2004/09/2004-09-02.csv.gz
us_stocks_sip/day_aggs_v1/2004/09/2004-09-03.csv.gz
us_stocks_sip/day_aggs_v1/2004/09/2004-09-07.csv.gz
us_stocks_sip/day_aggs_v1/2004/09/2004-09-08.csv.gz
us_stocks_sip/day_aggs_v1/2004/09/2004-09-09.csv.gz
us_stocks_sip/day_aggs_v1/2004/09/2004-09-10.csv.gz
us_stocks_sip/day_aggs_v1/2004/09/2004-09-13.csv.gz
us_stocks_sip/day_aggs_v1/2004/09/2004-09-14.csv.gz
us_stocks_sip/day_aggs_v1/2004/09/2004-09-15.csv.gz
us_stocks_sip/day_aggs_v1/2004/09/2004-09-16.csv.gz
us_stocks_sip/day_aggs_v1/2004/09/2004-09-17.csv.gz
us_stocks_sip/day_aggs_v1/2004/09/2004-09-20.csv.gz
us_stocks_sip/day_aggs_v1/2004/09/2004-09-21.csv.gz
us_stocks_sip/day_aggs_v1/2004/09/2004-09-22.csv.gz
us_stocks_sip/day_aggs_v1/2004/09/2004-09-23.csv.gz
us_stocks_sip/day_aggs_v1/2004/09/2004-09-24.csv.gz
us_stocks_sip/day_aggs_v1/2004/09/2004-09-27.csv.gz
us_stocks_sip/day_aggs_v1/2004/09/2004-09-28.csv.gz
us_stocks_sip/day_aggs_v1/2004/09/2004-09-29.csv.gz
us_stocks_sip/day_aggs_v1/2004/09/2004-09-30.csv.gz
us_stocks_sip/day_aggs_v1/2004/10/2004-10-01.csv.gz
us_stocks_sip/day_aggs_v1/2004/10/2004-10-04.csv.gz
us_stocks_sip/day_aggs_v1/2004/10/2004-10-05.csv.gz
us_stocks_sip/day_aggs_v1/2004/10/2004-10-06.csv.gz
us_stocks_sip/day_aggs_v1/2004/10/2004-10-07.csv.gz
us_stocks_sip/day_aggs_v1/2004/10/2004-10-08.csv.gz
us_stocks_sip/day_aggs_v1/2004/10/2004-10-11.csv.gz
us_stocks_sip/day_aggs_v1/2004/10/2004-10-12.csv.gz
us_stocks_sip/day_aggs_v1/2004/10/2004-10-13.csv.gz
us_stocks_sip/day_aggs_v1/2004/10/2004-10-14.csv.gz
us_stocks_sip/day_aggs_v1/2004/10/2004-10-15.csv.gz
us_stocks_sip/day_aggs_v1/2004/10/2004-10-18.csv.gz
us_stocks_sip/day_aggs_v1/2004/10/2004-10-19.csv.gz
us_stocks_sip/day_aggs_v1/2004/10/2004-10-20.csv.gz
us_stocks_sip/day_aggs_v1/2004/10/2004-10-21.csv.gz
us_stocks_sip/day_aggs_v1/2004/10/2004-10-22.csv.gz
us_stocks_sip/day_aggs_v1/2004/10/2004-10-25.csv.gz
us_stocks_sip/day_aggs_v1/2004/10/2004-10-26.csv.gz
us_stocks_sip/day_aggs_v1/2004/10/2004-10-27.csv.gz
us_stocks_sip/day_aggs_v1/2004/10/2004-10-28.csv.gz
us_stocks_sip/day_aggs_v1/2004/10/2004-10-29.csv.gz
us_stocks_sip/day_aggs_v1/2004/11/2004-11-01.csv.gz
us_stocks_sip/day_aggs_v1/2004/11/2004-11-02.csv.gz
us_stocks_sip/day_aggs_v1/2004/11/2004-11-03.csv.gz
us_stocks_sip/day_aggs_v1/2004/11/2004-11-04.csv.gz
us_stocks_sip/day_aggs_v1/2004/11/2004-11-05.csv.gz
us_stocks_sip/day_aggs_v1/2004/11/2004-11-08.csv.gz
us_stocks_sip/day_aggs_v1/2004/11/2004-11-09.csv.gz
us_stocks_sip/day_aggs_v1/2004/11/2004-11-10.csv.gz
us_stocks_sip/day_aggs_v1/2004/11/2004-11-11.csv.gz
us_stocks_sip/day_aggs_v1/2004/11/2004-11-12.csv.gz
us_stocks_sip/day_aggs_v1/2004/11/2004-11-15.csv.gz
us_stocks_sip/day_aggs_v1/2004/11/2004-11-16.csv.gz
us_stocks_sip/day_aggs_v1/2004/11/2004-11-17.csv.gz
us_stocks_sip/day_aggs_v1/2004/11/2004-11-18.csv.gz
us_stocks_sip/day_aggs_v1/2004/11/2004-11-19.csv.gz
us_stocks_sip/day_aggs_v1/2004/11/2004-11-22.csv.gz
us_stocks_sip/day_aggs_v1/2004/11/2004-11-23.csv.gz
us_stocks_sip/day_aggs_v1/2004/11/2004-11-24.csv.gz
us_stocks_sip/day_aggs_v1/2004/11/2004-11-26.csv.gz
us_stocks_sip/day_aggs_v1/2004/11/2004-11-29.csv.gz
us_stocks_sip/day_aggs_v1/2004/11/2004-11-30.csv.gz
us_stocks_sip/day_aggs_v1/2004/12/2004-12-01.csv.gz
us_stocks_sip/day_aggs_v1/2004/12/2004-12-02.csv.gz
us_stocks_sip/day_aggs_v1/2004/12/2004-12-03.csv.gz
us_stocks_sip/day_aggs_v1/2004/12/2004-12-06.csv.gz
us_stocks_sip/day_aggs_v1/2004/12/2004-12-07.csv.gz
us_stocks_sip/day_aggs_v1/2004/12/2004-12-08.csv.gz
us_stocks_sip/day_aggs_v1/2004/12/2004-12-09.csv.gz
us_stocks_sip/day_aggs_v1/2004/12/2004-12-10.csv.gz
us_stocks_sip/day_aggs_v1/2004/12/2004-12-13.csv.gz
us_stocks_sip/day_aggs_v1/2004/12/2004-12-14.csv.gz
us_stocks_sip/day_aggs_v1/2004/12/2004-12-15.csv.gz
us_stocks_sip/day_aggs_v1/2004/12/2004-12-16.csv.gz
us_stocks_sip/day_aggs_v1/2004/12/2004-12-17.csv.gz
us_stocks_sip/day_aggs_v1/2004/12/2004-12-20.csv.gz
us_stocks_sip/day_aggs_v1/2004/12/2004-12-21.csv.gz
us_stocks_sip/day_aggs_v1/2004/12/2004-12-22.csv.gz
us_stocks_sip/day_aggs_v1/2004/12/2004-12-23.csv.gz
us_stocks_sip/day_aggs_v1/2004/12/2004-12-27.csv.gz
us_stocks_sip/day_aggs_v1/2004/12/2004-12-28.csv.gz
us_stocks_sip/day_aggs_v1/2004/12/2004-12-29.csv.gz
us_stocks_sip/day_aggs_v1/2004/12/2004-12-30.csv.gz
us_stocks_sip/day_aggs_v1/2004/12/2004-12-31.csv.gz
us_stocks_sip/day_aggs_v1/2005/01/2005-01-03.csv.gz
us_stocks_sip/day_aggs_v1/2005/01/2005-01-04.csv.gz
us_stocks_sip/day_aggs_v1/2005/01/2005-01-05.csv.gz
us_stocks_sip/day_aggs_v1/2005/01/2005-01-06.csv.gz
us_stocks_sip/day_aggs_v1/2005/01/2005-01-07.csv.gz
us_stocks_sip/day_aggs_v1/2005/01/2005-01-10.csv.gz
us_stocks_sip/day_aggs_v1/2005/01/2005-01-11.csv.gz
us_stocks_sip/day_aggs_v1/2005/01/2005-01-12.csv.gz
us_stocks_sip/day_aggs_v1/2005/01/2005-01-13.csv.gz
us_stocks_sip/day_aggs_v1/2005/01/2005-01-14.csv.gz
us_stocks_sip/day_aggs_v1/2005/01/2005-01-18.csv.gz
us_stocks_sip/day_aggs_v1/2005/01/2005-01-19.csv.gz
us_stocks_sip/day_aggs_v1/2005/01/2005-01-20.csv.gz
us_stocks_sip/day_aggs_v1/2005/01/2005-01-21.csv.gz
us_stocks_sip/day_aggs_v1/2005/01/2005-01-24.csv.gz
us_stocks_sip/day_aggs_v1/2005/01/2005-01-25.csv.gz
us_stocks_sip/day_aggs_v1/2005/01/2005-01-26.csv.gz
us_stocks_sip/day_aggs_v1/2005/01/2005-01-27.csv.gz
us_stocks_sip/day_aggs_v1/2005/01/2005-01-28.csv.gz
us_stocks_sip/day_aggs_v1/2005/01/2005-01-31.csv.gz
us_stocks_sip/day_aggs_v1/2005/02/2005-02-01.csv.gz
us_stocks_sip/day_aggs_v1/2005/02/2005-02-02.csv.gz
us_stocks_sip/day_aggs_v1/2005/02/2005-02-03.csv.gz
us_stocks_sip/day_aggs_v1/2005/02/2005-02-04.csv.gz
us_stocks_sip/day_aggs_v1/2005/02/2005-02-07.csv.gz
us_stocks_sip/day_aggs_v1/2005/02/2005-02-08.csv.gz
us_stocks_sip/day_aggs_v1/2005/02/2005-02-09.csv.gz
us_stocks_sip/day_aggs_v1/2005/02/2005-02-10.csv.gz
us_stocks_sip/day_aggs_v1/2005/02/2005-02-11.csv.gz
us_stocks_sip/day_aggs_v1/2005/02/2005-02-14.csv.gz
us_stocks_sip/day_aggs_v1/2005/02/2005-02-15.csv.gz
us_stocks_sip/day_aggs_v1/2005/02/2005-02-16.csv.gz
us_stocks_sip/day_aggs_v1/2005/02/2005-02-17.csv.gz
us_stocks_sip/day_aggs_v1/2005/02/2005-02-18.csv.gz
us_stocks_sip/day_aggs_v1/2005/02/2005-02-22.csv.gz
us_stocks_sip/day_aggs_v1/2005/02/2005-02-23.csv.gz
us_stocks_sip/day_aggs_v1/2005/02/2005-02-24.csv.gz
us_stocks_sip/day_aggs_v1/2005/02/2005-02-25.csv.gz
us_stocks_sip/day_aggs_v1/2005/02/2005-02-28.csv.gz
us_stocks_sip/day_aggs_v1/2005/03/2005-03-01.csv.gz
us_stocks_sip/day_aggs_v1/2005/03/2005-03-02.csv.gz
us_stocks_sip/day_aggs_v1/2005/03/2005-03-03.csv.gz
us_stocks_sip/day_aggs_v1/2005/03/2005-03-04.csv.gz
us_stocks_sip/day_aggs_v1/2005/03/2005-03-07.csv.gz
us_stocks_sip/day_aggs_v1/2005/03/2005-03-08.csv.gz
us_stocks_sip/day_aggs_v1/2005/03/2005-03-09.csv.gz
us_stocks_sip/day_aggs_v1/2005/03/2005-03-10.csv.gz
us_stocks_sip/day_aggs_v1/2005/03/2005-03-11.csv.gz
us_stocks_sip/day_aggs_v1/2005/03/2005-03-14.csv.gz
us_stocks_sip/day_aggs_v1/2005/03/2005-03-15.csv.gz
us_stocks_sip/day_aggs_v1/2005/03/2005-03-16.csv.gz
us_stocks_sip/day_aggs_v1/2005/03/2005-03-17.csv.gz
us_stocks_sip/day_aggs_v1/2005/03/2005-03-18.csv.gz

In [16]:
# load large dataframe by chunking

import pandas as pd
from typing import List
ticker_list = [
    "AAPL",
    "MU",
]

import pandas as pd

def convert_timestamp_to_us_datetime(timestamp: int, unit="ms"):
    """
    Converts a millisecond timestamp to US/Eastern time.

    NYSE/NASDAQ are located at US/Eastern
    """
    return pd.to_datetime(
        timestamp, unit=unit, utc=True
    ).tz_convert('US/Eastern')      
    
def load_csv_by_chunking(
    filepath: str, ticker_list: List[str],
    chunk_size = 100000
):

    chunks = []
    for chunk in pd.read_csv(filepath, chunksize=chunk_size):
        filtered_chunk = chunk[chunk["ticker"].isin(ticker_list)]
        chunks.append(filtered_chunk)

    df = pd.concat(chunks)
    return df

In [20]:
filepath = "/Users/livardywufianto/Projects/Trading/vscode/technical-analysis/data/minute_aggs/2026-05-01.csv.gz"
df = load_csv_by_chunking(filepath, ticker_list)
df["us_datetime"] = df["window_start"].apply(
    lambda x: convert_timestamp_to_us_datetime(x, unit="ns"))
df["us_date"] = df["us_datetime"].dt.date
df["hour"] = df["us_datetime"].dt.hour

In [22]:
agg_logic = {
    "open": "first",    # The first price of the hour
    "high": "max",      # The highest price in that hour
    "low": "min",       # The lowest price in that hour
    "close": "last",    # The final price of the hour
    "volume": "sum",    # Total volume traded in that hour
    "transactions": "sum" # Total count of trades in that hour
}

hour_df = df.groupby(
    ["ticker", "us_date", "hour"]
).agg(agg_logic).reset_index()

In [23]:
hour_df

,ticker,us_date,hour,open,high,low,close,volume,transactions
0,AAPL,2026-05-01,4,278.000000,280.2200,277.5600,278.7800,2.637000e+05,8500
1,AAPL,2026-05-01,5,278.880000,280.4800,278.1500,279.7400,1.274838e+05,3884
2,AAPL,2026-05-01,6,279.790000,280.0000,279.0300,279.3800,8.000364e+04,2828
3,AAPL,2026-05-01,7,279.230000,282.4200,279.0500,281.2375,8.009688e+05,16184
4,AAPL,2026-05-01,8,281.230000,281.4700,280.0100,280.0500,8.078497e+05,14573
5,AAPL,2026-05-01,9,280.050000,284.7500,271.3500,283.9500,1.795586e+07,278859
6,AAPL,2026-05-01,10,283.950000,287.2200,282.0100,282.6100,1.534336e+07,312619
7,AAPL,2026-05-01,11,282.650000,285.4900,281.4600,284.7500,7.996999e+06,193978
8,AAPL,2026-05-01,12,284.710000,285.0000,282.3951,283.1170,8.643411e+06,125762
9,AAPL,2026-05-01,13,283.130000,283.5000,281.4200,281.4750,4.288033e+06,87485
10,AAPL,2026-05-01,14,281.475000,281.5400,280.1500,280.4500,4.818261e+06,95370
11,AAPL,2026-05-01,15,280.460000,280.8900,279.6100,280.1500,8.407762e+06,154536
12,AAPL,2026-05-01,16,280.140929,280.2600,279.7500,279.8300,7.494078e+05,3202
13,AAPL,2026-05-01,17,279.831000,280.0500,279.7300,279.8500,7.913207e+04,1390
14,AAPL,2026-05-01,18,279.850000,279.9200,279.8100,279.8500,3.281029e+04,879
15,AAPL,2026-05-01,19,279.880000,280.1400,279.8200,280.0700,4.133697e+04,1091
16,MU,2026-05-01,4,510.000000,511.6000,505.0000,505.8945,1.041205e+05,5770
17,MU,2026-05-01,5,505.600000,508.0000,504.5000,508.0000,4.143016e+04,1777
18,MU,2026-05-01,6,508.210000,509.5000,507.0100,508.8000,4.254345e+04,1674
19,MU,2026-05-01,7,508.510000,508.7000,505.4000,508.2812,1.507925e+05,4383
20,MU,2026-05-01,8,508.260000,511.7000,507.3000,508.9167,2.852563e+05,6856
21,MU,2026-05-01,9,508.990000,541.6380,508.2300,541.6380,8.361422e+06,156004
22,MU,2026-05-01,10,541.630000,545.9100,527.0100,527.6100,1.017873e+07,198727
23,MU,2026-05-01,11,527.620000,534.3200,524.7500,531.9900,4.356664e+06,90422
24,MU,2026-05-01,12,531.860000,534.7299,529.2200,531.0000,2.622951e+06,53503
25,MU,2026-05-01,13,531.000000,536.6299,528.4201,535.7800,3.093217e+06,50825
26,MU,2026-05-01,14,535.850000,543.3999,534.1000,540.1250,3.832440e+06,74179
27,MU,2026-05-01,15,540.125000,543.5700,538.0000,542.3600,5.016426e+06,99925
28,MU,2026-05-01,16,542.210000,542.9100,539.8096,540.4100,2.373212e+05,6910
29,MU,2026-05-01,17,540.500000,540.7900,540.0000,540.1000,7.013898e+04,2182
30,MU,2026-05-01,18,540.140000,540.7029,540.0000,540.2200,4.309832e+04,1517
31,MU,2026-05-01,19,540.200000,540.3700,539.1600,539.9100,6.379646e+04,1985

In [ ]:
# 1. Ensure us_datetime is the index
df = df.set_index("us_datetime")

# 2. Define the aggregation logic for each column
agg_logic = {
    "open": "first",    # The first price of the hour
    "high": "max",      # The highest price in that hour
    "low": "min",       # The lowest price in that hour
    "close": "last",    # The final price of the hour
    "volume": "sum",    # Total volume traded in that hour
    "transactions": "sum" # Total count of trades in that hour
}

# 3. Resample to 1 Hour ('H')
hourly_df = df.resample("H").agg(agg_logic).dropna()

# 4. Clean up
hourly_df = hourly_df.reset_index()

In [12]:
import pandas as pd

# Pandas handles decompression on the fly
filepath = "/Users/livardywufianto/Projects/Trading/vscode/technical-analysis/data/2025-11-05.csv.gz"
filepath = "/Users/livardywufianto/Projects/Trading/vscode/technical-analysis/data/2026-05-08.csv.gz"
filepath = "/Users/livardywufianto/Projects/Trading/vscode/technical-analysis/data/minute_aggs/2026-05-01.csv.gz"
df = pd.read_csv(filepath, nrows=500)

In [14]:
stock = ["ICHR", "POET"]

,ticker,volume,open,close,high,low,window_start,transactions,us_datetime
0,A,10805.484156,116.130,115.665,116.275,115.665,1777642200000000000,74,2026-05-01 09:30:00-04:00
1,A,1617.024991,115.270,115.755,115.920,115.270,1777642260000000000,23,2026-05-01 09:31:00-04:00
2,A,8080.000000,115.705,115.685,115.705,115.685,1777642320000000000,34,2026-05-01 09:32:00-04:00
3,A,7933.137804,115.705,115.390,115.705,115.390,1777642380000000000,62,2026-05-01 09:33:00-04:00
4,A,2832.000000,115.390,115.535,115.535,115.235,1777642440000000000,47,2026-05-01 09:34:00-04:00
...,...,...,...,...,...,...,...,...,...
495,AA,3664.216000,63.320,63.320,63.340,63.300,1777648620000000000,66,2026-05-01 11:17:00-04:00
496,AA,7597.300000,63.350,63.270,63.360,63.270,1777648680000000000,161,2026-05-01 11:18:00-04:00
497,AA,1445.072000,63.310,63.340,63.340,63.310,1777648740000000000,51,2026-05-01 11:19:00-04:00
498,AA,5736.958118,63.350,63.400,63.420,63.350,1777648800000000000,87,2026-05-01 11:20:00-04:00
499,AA,1991.378659,63.370,63.385,63.395,63.370,1777648860000000000,92,2026-05-01 11:21:00-04:00